version: 2
updates:

- package-ecosystem: gomod
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - valentinocossar
  assignees:
    - casvaldot
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
