builds:
  -
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X hssh/cmd.Version={{.Tag}}

brews:
  -
    name: hssh
    tap:
      owner: heply
      name: homebrew-tap
    folder: Formula
    description: "A CLI to easily sync, list, search and connect to SSH hosts"
    license: "MIT"
    dependencies:
      - name: fzf
